version: "3"

services:
  # mysql_db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: testdb
  #     MYSQL_USER: root2
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - 3306:3306
  python3:
    build: .
    # depends_on:
    #   - mysql_db
    volumes:
      - ./server:/srv:cached
    ports:
      - 5000:80
