version: "3"

services:
  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  python3:
    build: .
    depends_on:
      - mysql_db
    ports:
      - 5000:80
